# Generated by Django 2.2.24 on 2023-07-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Год постройки здания'),
        ),
    ]
