# Generated by Django 2.2.24 on 2023-07-14 07:01

from django.db import migrations

import phonenumbers
from django.db.transaction import TransactionManagementError


def add_valid_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = f'+7{phonenumbers.parse(flat.owners_phonenumber, "RU").national_number}'
        valid_number = phonenumbers.parse(pure_phone, 'RU')
        if phonenumbers.is_valid_number(valid_number):
            flat.owner_pure_phone = valid_number
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(add_valid_phonenumbers)
    ]
