# Generated by Django 2.2.24 on 2023-07-16 12:06

from django.db import migrations


def get_owners_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner, _ = Owner.objects.get_or_create(owner=flat.owner, phone=flat.owners_phonenumber,
                                               pure_phone=flat.owner_pure_phone)
        owner.owned_flats.add(flat.id)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(get_owners_info)
    ]
